# -*- coding: utf-8 -*-
"""Ⅰ.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bCIAUWTq7Y7n8zhfGnKImTd8F-cczYem
"""

print("# 하나만 출력합니다.")

print("Hello Python Programming...!")

print()

print("# 여러 개를 출력합니다.")

print(10, 20, 30, 40, 50)

print("안녕하세요", "저의", "이름은", "윤인성입니다!")

print()

print("# 아무것도 출력하지 않습니다.")

print("--- 확인 전용선 ---")

print()

print()

print("--- 확인 전용선 ---")

